version: '3.8'

services:
  frontend:
    image: react-vite-app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
